// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Gender int64

const (
	Gender_MALE   Gender = 1
	Gender_FEMALE Gender = 2
)

func (p Gender) String() string {
	switch p {
	case Gender_MALE:
		return "MALE"
	case Gender_FEMALE:
		return "FEMALE"
	}
	return "<UNSET>"
}

func GenderFromString(s string) (Gender, error) {
	switch s {
	case "MALE":
		return Gender_MALE, nil
	case "FEMALE":
		return Gender_FEMALE, nil
	}
	return Gender(0), fmt.Errorf("not a valid Gender string")
}

func GenderPtr(v Gender) *Gender { return &v }
func (p *Gender) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Gender(result.Int64)
	return
}

func (p *Gender) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type User struct {
	Id      int64    `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name    string   `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Email   string   `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Age     int32    `thrift:"age,4" frugal:"4,default,i32" json:"age"`
	Address string   `thrift:"address,5" frugal:"5,default,string" json:"address"`
	Tags    []string `thrift:"tags,6" frugal:"6,default,list<string>" json:"tags"`
	Gender  Gender   `thrift:"gender,7" frugal:"7,default,Gender" json:"gender"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetAge() (v int32) {
	return p.Age
}

func (p *User) GetAddress() (v string) {
	return p.Address
}

func (p *User) GetTags() (v []string) {
	return p.Tags
}

func (p *User) GetGender() (v Gender) {
	return p.Gender
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetAge(val int32) {
	p.Age = val
}
func (p *User) SetAddress(val string) {
	p.Address = val
}
func (p *User) SetTags(val []string) {
	p.Tags = val
}
func (p *User) SetGender(val Gender) {
	p.Gender = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "name",
	3: "email",
	4: "age",
	5: "address",
	6: "tags",
	7: "gender",
}

type GetUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "user_id",
}

type GetUserResponse struct {
	User    *User  `thrift:"user,1" frugal:"1,default,User" json:"user"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_User_DEFAULT *User

func (p *GetUserResponse) GetUser() (v *User) {
	if !p.IsSetUser() {
		return GetUserResponse_User_DEFAULT
	}
	return p.User
}

func (p *GetUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *GetUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *GetUserResponse) SetUser(val *User) {
	p.User = val
}
func (p *GetUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *GetUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *GetUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "user",
	2: "code",
	3: "message",
}

type CreateUserRequest struct {
	Name    string   `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Email   string   `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Age     int32    `thrift:"age,3" frugal:"3,default,i32" json:"age"`
	Address string   `thrift:"address,4" frugal:"4,default,string" json:"address"`
	Tags    []string `thrift:"tags,5" frugal:"5,default,list<string>" json:"tags"`
}

func NewCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{}
}

func (p *CreateUserRequest) InitDefault() {
}

func (p *CreateUserRequest) GetName() (v string) {
	return p.Name
}

func (p *CreateUserRequest) GetEmail() (v string) {
	return p.Email
}

func (p *CreateUserRequest) GetAge() (v int32) {
	return p.Age
}

func (p *CreateUserRequest) GetAddress() (v string) {
	return p.Address
}

func (p *CreateUserRequest) GetTags() (v []string) {
	return p.Tags
}
func (p *CreateUserRequest) SetName(val string) {
	p.Name = val
}
func (p *CreateUserRequest) SetEmail(val string) {
	p.Email = val
}
func (p *CreateUserRequest) SetAge(val int32) {
	p.Age = val
}
func (p *CreateUserRequest) SetAddress(val string) {
	p.Address = val
}
func (p *CreateUserRequest) SetTags(val []string) {
	p.Tags = val
}

func (p *CreateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserRequest(%+v)", *p)
}

var fieldIDToName_CreateUserRequest = map[int16]string{
	1: "name",
	2: "email",
	3: "age",
	4: "address",
	5: "tags",
}

type CreateUserResponse struct {
	UserId  int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewCreateUserResponse() *CreateUserResponse {
	return &CreateUserResponse{}
}

func (p *CreateUserResponse) InitDefault() {
}

func (p *CreateUserResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *CreateUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *CreateUserResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *CreateUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *CreateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResponse(%+v)", *p)
}

var fieldIDToName_CreateUserResponse = map[int16]string{
	1: "user_id",
	2: "code",
	3: "message",
}

type UpdateUserRequest struct {
	Id      int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name    *string `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Email   *string `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
	Age     *int32  `thrift:"age,4,optional" frugal:"4,optional,i32" json:"age,omitempty"`
	Address *string `thrift:"address,5,optional" frugal:"5,optional,string" json:"address,omitempty"`
}

func NewUpdateUserRequest() *UpdateUserRequest {
	return &UpdateUserRequest{}
}

func (p *UpdateUserRequest) InitDefault() {
}

func (p *UpdateUserRequest) GetId() (v int64) {
	return p.Id
}

var UpdateUserRequest_Name_DEFAULT string

func (p *UpdateUserRequest) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateUserRequest_Name_DEFAULT
	}
	return *p.Name
}

var UpdateUserRequest_Email_DEFAULT string

func (p *UpdateUserRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UpdateUserRequest_Email_DEFAULT
	}
	return *p.Email
}

var UpdateUserRequest_Age_DEFAULT int32

func (p *UpdateUserRequest) GetAge() (v int32) {
	if !p.IsSetAge() {
		return UpdateUserRequest_Age_DEFAULT
	}
	return *p.Age
}

var UpdateUserRequest_Address_DEFAULT string

func (p *UpdateUserRequest) GetAddress() (v string) {
	if !p.IsSetAddress() {
		return UpdateUserRequest_Address_DEFAULT
	}
	return *p.Address
}
func (p *UpdateUserRequest) SetId(val int64) {
	p.Id = val
}
func (p *UpdateUserRequest) SetName(val *string) {
	p.Name = val
}
func (p *UpdateUserRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *UpdateUserRequest) SetAge(val *int32) {
	p.Age = val
}
func (p *UpdateUserRequest) SetAddress(val *string) {
	p.Address = val
}

func (p *UpdateUserRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateUserRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UpdateUserRequest) IsSetAge() bool {
	return p.Age != nil
}

func (p *UpdateUserRequest) IsSetAddress() bool {
	return p.Address != nil
}

func (p *UpdateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserRequest = map[int16]string{
	1: "id",
	2: "name",
	3: "email",
	4: "age",
	5: "address",
}

type UpdateUserResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewUpdateUserResponse() *UpdateUserResponse {
	return &UpdateUserResponse{}
}

func (p *UpdateUserResponse) InitDefault() {
}

func (p *UpdateUserResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *UpdateUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *UpdateUserResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *UpdateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserResponse = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type DeleteUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewDeleteUserRequest() *DeleteUserRequest {
	return &DeleteUserRequest{}
}

func (p *DeleteUserRequest) InitDefault() {
}

func (p *DeleteUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserRequest(%+v)", *p)
}

var fieldIDToName_DeleteUserRequest = map[int16]string{
	1: "user_id",
}

type DeleteUserResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewDeleteUserResponse() *DeleteUserResponse {
	return &DeleteUserResponse{}
}

func (p *DeleteUserResponse) InitDefault() {
}

func (p *DeleteUserResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeleteUserResponse) GetCode() (v int32) {
	return p.Code
}

func (p *DeleteUserResponse) GetMessage() (v string) {
	return p.Message
}
func (p *DeleteUserResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteUserResponse) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteUserResponse) SetMessage(val string) {
	p.Message = val
}

func (p *DeleteUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserResponse(%+v)", *p)
}

var fieldIDToName_DeleteUserResponse = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type ListUsersRequest struct {
	Page     int32   `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize int32   `thrift:"page_size,2" frugal:"2,default,i32" json:"page_size"`
	Keyword  *string `thrift:"keyword,3,optional" frugal:"3,optional,string" json:"keyword,omitempty"`
}

func NewListUsersRequest() *ListUsersRequest {
	return &ListUsersRequest{}
}

func (p *ListUsersRequest) InitDefault() {
}

func (p *ListUsersRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListUsersRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var ListUsersRequest_Keyword_DEFAULT string

func (p *ListUsersRequest) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return ListUsersRequest_Keyword_DEFAULT
	}
	return *p.Keyword
}
func (p *ListUsersRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListUsersRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListUsersRequest) SetKeyword(val *string) {
	p.Keyword = val
}

func (p *ListUsersRequest) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *ListUsersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersRequest(%+v)", *p)
}

var fieldIDToName_ListUsersRequest = map[int16]string{
	1: "page",
	2: "page_size",
	3: "keyword",
}

type ListUsersResponse struct {
	Users   []*User `thrift:"users,1" frugal:"1,default,list<User>" json:"users"`
	Total   int32   `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	Code    int32   `thrift:"code,3" frugal:"3,default,i32" json:"code"`
	Message string  `thrift:"message,4" frugal:"4,default,string" json:"message"`
}

func NewListUsersResponse() *ListUsersResponse {
	return &ListUsersResponse{}
}

func (p *ListUsersResponse) InitDefault() {
}

func (p *ListUsersResponse) GetUsers() (v []*User) {
	return p.Users
}

func (p *ListUsersResponse) GetTotal() (v int32) {
	return p.Total
}

func (p *ListUsersResponse) GetCode() (v int32) {
	return p.Code
}

func (p *ListUsersResponse) GetMessage() (v string) {
	return p.Message
}
func (p *ListUsersResponse) SetUsers(val []*User) {
	p.Users = val
}
func (p *ListUsersResponse) SetTotal(val int32) {
	p.Total = val
}
func (p *ListUsersResponse) SetCode(val int32) {
	p.Code = val
}
func (p *ListUsersResponse) SetMessage(val string) {
	p.Message = val
}

func (p *ListUsersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersResponse(%+v)", *p)
}

var fieldIDToName_ListUsersResponse = map[int16]string{
	1: "users",
	2: "total",
	3: "code",
	4: "message",
}

type UserService interface {
	GetUser(ctx context.Context, request *GetUserRequest) (r *GetUserResponse, err error)

	CreateUser(ctx context.Context, request *CreateUserRequest) (r *CreateUserResponse, err error)

	UpdateUser(ctx context.Context, request *UpdateUserRequest) (r *UpdateUserResponse, err error)

	DeleteUser(ctx context.Context, request *DeleteUserRequest) (r *DeleteUserResponse, err error)

	ListUsers(ctx context.Context, request *ListUsersRequest) (r *ListUsersResponse, err error)
}

type UserServiceGetUserArgs struct {
	Request *GetUserRequest `thrift:"request,1" frugal:"1,default,GetUserRequest" json:"request"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Request_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetRequest() (v *GetUserRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetUserArgs) SetRequest(val *GetUserRequest) {
	p.Request = val
}

func (p *UserServiceGetUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "request",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceCreateUserArgs struct {
	Request *CreateUserRequest `thrift:"request,1" frugal:"1,default,CreateUserRequest" json:"request"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Request_DEFAULT *CreateUserRequest

func (p *UserServiceCreateUserArgs) GetRequest() (v *CreateUserRequest) {
	if !p.IsSetRequest() {
		return UserServiceCreateUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceCreateUserArgs) SetRequest(val *CreateUserRequest) {
	p.Request = val
}

func (p *UserServiceCreateUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserArgs = map[int16]string{
	1: "request",
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserResponse" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResponse

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResponse)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserArgs struct {
	Request *UpdateUserRequest `thrift:"request,1" frugal:"1,default,UpdateUserRequest" json:"request"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Request_DEFAULT *UpdateUserRequest

func (p *UserServiceUpdateUserArgs) GetRequest() (v *UpdateUserRequest) {
	if !p.IsSetRequest() {
		return UserServiceUpdateUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceUpdateUserArgs) SetRequest(val *UpdateUserRequest) {
	p.Request = val
}

func (p *UserServiceUpdateUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "request",
}

type UserServiceUpdateUserResult struct {
	Success *UpdateUserResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *UpdateUserResponse

func (p *UserServiceUpdateUserResult) GetSuccess() (v *UpdateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResponse)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteUserArgs struct {
	Request *DeleteUserRequest `thrift:"request,1" frugal:"1,default,DeleteUserRequest" json:"request"`
}

func NewUserServiceDeleteUserArgs() *UserServiceDeleteUserArgs {
	return &UserServiceDeleteUserArgs{}
}

func (p *UserServiceDeleteUserArgs) InitDefault() {
}

var UserServiceDeleteUserArgs_Request_DEFAULT *DeleteUserRequest

func (p *UserServiceDeleteUserArgs) GetRequest() (v *DeleteUserRequest) {
	if !p.IsSetRequest() {
		return UserServiceDeleteUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceDeleteUserArgs) SetRequest(val *DeleteUserRequest) {
	p.Request = val
}

func (p *UserServiceDeleteUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceDeleteUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserArgs = map[int16]string{
	1: "request",
}

type UserServiceDeleteUserResult struct {
	Success *DeleteUserResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteUserResult() *UserServiceDeleteUserResult {
	return &UserServiceDeleteUserResult{}
}

func (p *UserServiceDeleteUserResult) InitDefault() {
}

var UserServiceDeleteUserResult_Success_DEFAULT *DeleteUserResponse

func (p *UserServiceDeleteUserResult) GetSuccess() (v *DeleteUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserResponse)
}

func (p *UserServiceDeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserResult = map[int16]string{
	0: "success",
}

type UserServiceListUsersArgs struct {
	Request *ListUsersRequest `thrift:"request,1" frugal:"1,default,ListUsersRequest" json:"request"`
}

func NewUserServiceListUsersArgs() *UserServiceListUsersArgs {
	return &UserServiceListUsersArgs{}
}

func (p *UserServiceListUsersArgs) InitDefault() {
}

var UserServiceListUsersArgs_Request_DEFAULT *ListUsersRequest

func (p *UserServiceListUsersArgs) GetRequest() (v *ListUsersRequest) {
	if !p.IsSetRequest() {
		return UserServiceListUsersArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceListUsersArgs) SetRequest(val *ListUsersRequest) {
	p.Request = val
}

func (p *UserServiceListUsersArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceListUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersArgs = map[int16]string{
	1: "request",
}

type UserServiceListUsersResult struct {
	Success *ListUsersResponse `thrift:"success,0,optional" frugal:"0,optional,ListUsersResponse" json:"success,omitempty"`
}

func NewUserServiceListUsersResult() *UserServiceListUsersResult {
	return &UserServiceListUsersResult{}
}

func (p *UserServiceListUsersResult) InitDefault() {
}

var UserServiceListUsersResult_Success_DEFAULT *ListUsersResponse

func (p *UserServiceListUsersResult) GetSuccess() (v *ListUsersResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListUsersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListUsersResponse)
}

func (p *UserServiceListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersResult(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersResult = map[int16]string{
	0: "success",
}
